marketplace_validation/img_check.sh
apt-check should always be present on snapshot created images using a supported version of Ubuntu.  This is an edge case unless we are hitting this at times we should not.
A new check and error message has been added but the script will still exit if apt-check is not found since it will not be able to detect if security updates are needed.
=> Fix for Issue 8 - script crashes if apt-check is not present on Ubuntu

marketplace_docs/build-an-image.md
Updated clean-up script to use apt instead of apt-get.
apt is the newer tool and it works better than simple apt-get. If apt-get is used, not all security patches get installed and img_check.sh will fail. Note that apt-get can also be used, but is has to be enhanced with additional flags like  --with-new-pkgs and etc. I think apt is the more appropriate solution.
=> Changed apt-get to apt

scripts/img_check.sh
Changes to how we calculate the number of security updates that are available and in how we list update-able packages.
=> Fixes for security update checks on Ubuntu/Debian

packer/marketplace-image.json
This PR fixes https://github.com/digitalocean/marketplace-partners/issues/67 by making the following changes:
- Wait for cloud-init to complete before updating/installing packages. Otherwise the package update/upgrade runs in parallel with `cloud-init`, which can lead to funky behavior.
- Switch to using `apt` instead of `apt-get` since it is ["the most recommended interface"](https://debian-handbook.info/browse/stable/sect.apt-get.html)).
- Switch `apt-get upgrade` to `apt full-upgrade`. This will remove some obsolete packages or install new dependencies if required and is the reason `apt-check` reports an inconsistent list of security updates. `full-updates` should be safe to use because no packages have been installed at this point.
=> Use apt and wait for cloud-init

README.md, scripts/img_check.sh
Adds support for Debian 10 to img_chcek.sh
Adds Debian 10 to list of supported distros in the Readme
Removes CentOS 6 from the list of supported distros in the readme (EOL soon)
=> Add Debian 10

scripts/img_check.sh
to pipe through head -1 so we check the first line of the response only
tested on ubuntu 18.04 and 16.04 OK. 
with thanks to @lulugo for this suggestion https://github.com/digitalocean/marketplace-partners/issues/74#issuecomment-541245196
=> update ufw check on Ubuntu 

scripts/cleanup.sh
There's a rare issue that can occur with certain ssh configurations where ssh login using key based auth will be refused: 
- if /etc/ssh/revoked_keys does not exist OR
- if /etc/ssh/revoked_keys has permissions that are not mode 600 
This PR should address that issue by ensuring the revoked_keys file exists, is zero bytes, and has mode 600 set.
=> cleanup.sh: revoked_keys ssh bug fix

scripts/cleanup.sh
Print additional information to stdout to inform the user of why the dd is being performed, what to expect, and provide some output to let the user know the dd is still working.
=> Provide more info to user on dd operation.

README.md
Moving some text around so that automated build mention and links appears in a more logical place.
=> README.md: copy edits re: automated builds

scripts/img_check.sh
**BACKGROUND**
https://github.com/digitalocean/marketplace-partners/issues/60
We want to check to make sure that the output log doesn't contain any SHA256 values inside of it and fail if it does.
**CHANGES**
* add a specific check for the `cloud-init-output.log` file and search for the `SHA256` value and fail if it's found.
cc @arosales
=> Issue 60 check for key in log

scripts/img_check.sh
Reverts digitalocean/marketplace-partners#98
this is throwing too many false negatives on the test. we want to remove it.
=> Revert "Issue 60 check for key in log"

scripts/cleanup.sh, scripts/img_check.sh
apt-get update fails if the /tmp directory doesn't exist or has
incorrect permissions. Before checking for security updates, create
the /tmp directory if it doesn't exist.
https://github.com/digitalocean/marketplace-partners/issues/94
=> Create /tmp before checking for updates

scripts/cleanup.sh
Conditionally execute `apt-get` or `yum` commands as appropriate. Add `errexit` option to exit when one command fails.
=> Make cleanup.sh run on CentOS

scripts/img_check.sh
Returning an error code on WARNings is a bit misleading. Makes more sense to return a "success" code, or at the very least return a different exit code to differentiate from FAILure cases
=> updated exit code for warnings

scripts/90-cleanup.sh
This solves two issues
1. `apt-get upgrade` does not reliably upgrade the system. I'm not really confident the incantation I have in this PR covers all cases, but it does cover what I'm trying to do right now. Currently, if you attempt to upgrade digitalocean's Ubuntu 20.04 image using simply `apt-get upgrade`, apt will prompt the user for a decision about what to do about openssh configuration. `--force-yes`, `-y` and other options are not sufficient to suppress it, so I had to pass an option that I'm going to keep the old config
2. The `dd` command is too slow, but it can be sped up substantially if you specify a block size. 4096 is a common choice since it is a typical block size.
I also erased lines that truncated lastlog and wtmp since it looked like that was already being truncated …
=> small improvements

scripts/99-img-check.sh
**Description**
DO is going to support Rocky linux and Centos stream in August, so img-check should be updated
**What this PR adds** 
Img check is updated to accept these OSs.
=> [MP-3865] add rocky linux and centos stream to supported OSs

scripts/99-img-check.sh
**Description**
Ubuntu 22.04 is not supported in img-check.sh script (found there - https://github.com/digitalocean/marketplace-partners/issues/150)
**What PR does**
Adds support for Ubuntu 22.04
**Proof**
Before:
After:
=> Add support for ubuntu 22 04

scripts/99-img-check.sh
Debian 11 is a modern and stable distro. It was released a long time ago, and it works exactly as stable as Debian 10 (buster).
=> Add Debian 11 (bullseye) support

scripts/99-img-check.sh
The conditional for ip_tables check fails when ip_tables is present. This change fixes the check.
closes #136
=> Fix ip_tables check in img-check

scripts/99-img-check.sh
The DO agent lives in a different location than where the check is looking. Update the conditional to check for existence of do_agent file at correct location.
closes #154
=> Fix DO agent check in img-check

scripts/99-img-check.sh
The DO agent check, checks for the presence of a directory under /opt/digitalocean. The name of this directly slightly varies between various distributions. Rather than check a sub-directory, simply check for the existence of the /opt/digitalocean directory which is consistent between distributions and does not exist if the DO agent or monitoring are installed. Also, update the instructions for properly cleaning up if removing a previously installed agent and include Debian.
=> Improve DO agent check

README.md, scripts/99-img-check.sh
CentOS Stream 9 image is already available on the market, but it not supported by img_check.sh still.
=> Add CentOS Stream 9 support

README.md
There is `version` in the patch vp APP path, but it's not used anymore. Now it just confuses time from time. This PR adds new endpoint to the Readme and notes that old one is deprecated.
=> Update app VP patch endpoint
