digitalocean/marketplace-partners

marketplace_validation/img_check.sh

@ryanpq can you take a look? This would address https://github.com/digitalocean/marketplace-partners/issues/17

img_check.sh: list the uninstalled security packages

---

marketplace_validation/img_check.sh

Assists in debugging efforts that may come up between DO and Vendors, as well as in DO's listing submission process. // @ryanpq

img_check.sh: Print date that script is run

---

marketplace_docs/build-an-image.md

build-an-image.md: doctl instructions added

---

CHANGELOG.md
README.md
marketplace_docs/build-an-image.md
marketplace_validation/img_check.sh

- add support to image test script for Debian
- update README's
- for more info on changelog hooks please ref: <https://github.com/dOpensource/dsiprouter/tree/dev/resources/git>

Add Support for Debian 9

---

marketplace_validation/img_check.sh

Improves firewall detection for UFW on Ubuntu and Debian by ensuring that ufw is both installed and enabled.

Rewrite of firewall detection to imrpove UFW detection

---

getting-started.md

We don't allow BYOI/custom images into the Marketplace at this point, so we should remove that mention from the page. // @hazel-nut

getting-started.md: Snapshot recommendation removal

---

scripts/README.md

README.md: 1st version

---

fabric/template/fabfile.py

I didn't test this yet. Just cleaned up all the flake8 errors.

Eliminate flake8 errors

---

.github/CODEOWNERS

This adds mp-eng as a codeowner so that we get notified on every pr or issue.

Create CODEOWNERS file for mp-eng

---

.github/CONTRIBUTING.md
README.md
packer/files/var/lib/cloud/scripts/per-instance/001_onboot
scripts/img_check.sh

@hazel-nut mind taking a look at this one? Keeping it really simple by design but I'm open to any suggestions you might have to make it a bit better at the outset. You might recognize some of the language, too ;) Thanks!

Add basic contributing guidelines

---

scripts/img_check.sh

**Background**
https://github.com/digitalocean/marketplace-partners/issues/49
This was an issue where we would return a failure if there were empty files. This makes sure that if the file is empty we only warn.
**Changes**
* We were currently doing a `!=` on the id_rsa which IS a private key. This changes it so the check is this:
`first: authorized_keys --> second: id_rsa --> third: anything else except known_hosts --> last: known_hosts`
* This removed a bunch of whitespace issues too.
* add if else on the id_rsa that only warns if the file is empty.

handle files correctly

---

README.md

Added specifics about how to:
- access Vendor Portal
- submit DOKS 1-Click Apps

README.md: clarify app submission process

---

getting-started.md
packer/README.md

This should address https://github.com/digitalocean/marketplace-partners/issues/110.

Fix Packer broken links in docs

---

scripts/img_check.sh

Fix problem with UFW check on img_check.sh for Debian

---

packer/scripts/99-img_check.sh

This PR checks for missing security updates on a centos image.

centos security updates check

---

scripts/99-img-check.sh

Reverts digitalocean/marketplace-partners#143
Reverting due to us being unable to publish custom images in the marketplace, this was unknown at the time of this PR merging.

Revert "Add AlmaLinux OS support"

---

scripts/99-img-check.sh

[MP-4049](https://jira.internal.digitalocean.com/browse/MP-4049)
In this PR:
Remove the MongoDB check from the image_check script

Mp 4049/remove mongo db check

---

scripts/99-img-check.sh

Address shellcheck errors and fix some PASS/FAIL counting errors discovered. Also, addresses an issue with iptables checking discovered by shellcheck but this is also addressed separately in another PR/commit.
closes #153

Address shellcheck errors

---

scripts/99-img-check.sh

Meaninful changes were made to the image check script. Bump the version number.

Bump version number of image check script

---

scripts/99-img-check.sh

There are several commits between the last version bump and the main branch. Bump the version.

Bump the version of the image check script

---

README.md

Fix two 404 links in README.md

---

README.md

Adds section to readme on how to update an app via the API.

Add API update information
